package com.zt.dao;

import com.zt.pojo.SlDataBasketballWithBLOBs;

import java.util.List;

public interface SlDataBasketballMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sl_data_basketball
     *
     * @mbggenerated
     */
    int insert(SlDataBasketballWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sl_data_basketball
     *
     * @mbggenerated
     */
    int insertSelective(SlDataBasketballWithBLOBs record);

    /**
     * 根据id查询
     * @param id
     * @return
     */
    List<SlDataBasketballWithBLOBs> findById(String id);
}