package com.zt.dao;


import com.zt.pojo.SlDataTradWithBLOBs;

import java.util.List;

/**
 * 传统足彩接口
 */
public interface SlDataTradMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sl_data_trad
     *插入
     * @mbggenerated
     */
    int insert(SlDataTradWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sl_data_trad
     *批量插入
     * @mbggenerated
     */
    int insertSelective(SlDataTradWithBLOBs record);


    //根据期号查询
    List<SlDataTradWithBLOBs> findByDate(String number);
}