package com.zt.pojo;

public class SlDataBasketballWithBLOBs extends SlDataBasketball {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.event_id
     *
     * @mbggenerated
     */
    private String eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.data_id
     *
     * @mbggenerated
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.number_of_periods
     *
     * @mbggenerated
     */
    private String numberOfPeriods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.lottery_type
     *
     * @mbggenerated
     */
    private String lotteryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.data_type
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.period
     *
     * @mbggenerated
     */
    private String period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.num_id
     *
     * @mbggenerated
     */
    private String numId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.num_name
     *
     * @mbggenerated
     */
    private String numName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.start_date
     *
     * @mbggenerated
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.start_time
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.event_date
     *
     * @mbggenerated
     */
    private String eventDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.event_type
     *
     * @mbggenerated
     */
    private String eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.event_type_abrv
     *
     * @mbggenerated
     */
    private String eventTypeAbrv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.home
     *
     * @mbggenerated
     */
    private String home;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.home_abrv
     *
     * @mbggenerated
     */
    private String homeAbrv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.visitor
     *
     * @mbggenerated
     */
    private String visitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.visitor_abrv
     *
     * @mbggenerated
     */
    private String visitorAbrv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.event_bg_color
     *
     * @mbggenerated
     */
    private String eventBgColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.contents
     *
     * @mbggenerated
     */
    private String contents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.home_score
     *
     * @mbggenerated
     */
    private String homeScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.visitor_score
     *
     * @mbggenerated
     */
    private String visitorScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.created
     *
     * @mbggenerated
     */
    private String created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_data_basketball.updated
     *
     * @mbggenerated
     */
    private String updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.event_id
     *
     * @return the value of Sl_data_basketball.event_id
     *
     * @mbggenerated
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.event_id
     *
     * @param eventId the value for Sl_data_basketball.event_id
     *
     * @mbggenerated
     */
    public void setEventId(String eventId) {
        this.eventId = eventId == null ? null : eventId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.data_id
     *
     * @return the value of Sl_data_basketball.data_id
     *
     * @mbggenerated
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.data_id
     *
     * @param dataId the value for Sl_data_basketball.data_id
     *
     * @mbggenerated
     */
    public void setDataId(String dataId) {
        this.dataId = dataId == null ? null : dataId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.number_of_periods
     *
     * @return the value of Sl_data_basketball.number_of_periods
     *
     * @mbggenerated
     */
    public String getNumberOfPeriods() {
        return numberOfPeriods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.number_of_periods
     *
     * @param numberOfPeriods the value for Sl_data_basketball.number_of_periods
     *
     * @mbggenerated
     */
    public void setNumberOfPeriods(String numberOfPeriods) {
        this.numberOfPeriods = numberOfPeriods == null ? null : numberOfPeriods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.lottery_type
     *
     * @return the value of Sl_data_basketball.lottery_type
     *
     * @mbggenerated
     */
    public String getLotteryType() {
        return lotteryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.lottery_type
     *
     * @param lotteryType the value for Sl_data_basketball.lottery_type
     *
     * @mbggenerated
     */
    public void setLotteryType(String lotteryType) {
        this.lotteryType = lotteryType == null ? null : lotteryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.data_type
     *
     * @return the value of Sl_data_basketball.data_type
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.data_type
     *
     * @param dataType the value for Sl_data_basketball.data_type
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.period
     *
     * @return the value of Sl_data_basketball.period
     *
     * @mbggenerated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.period
     *
     * @param period the value for Sl_data_basketball.period
     *
     * @mbggenerated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.num_id
     *
     * @return the value of Sl_data_basketball.num_id
     *
     * @mbggenerated
     */
    public String getNumId() {
        return numId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.num_id
     *
     * @param numId the value for Sl_data_basketball.num_id
     *
     * @mbggenerated
     */
    public void setNumId(String numId) {
        this.numId = numId == null ? null : numId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.num_name
     *
     * @return the value of Sl_data_basketball.num_name
     *
     * @mbggenerated
     */
    public String getNumName() {
        return numName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.num_name
     *
     * @param numName the value for Sl_data_basketball.num_name
     *
     * @mbggenerated
     */
    public void setNumName(String numName) {
        this.numName = numName == null ? null : numName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.start_date
     *
     * @return the value of Sl_data_basketball.start_date
     *
     * @mbggenerated
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.start_date
     *
     * @param startDate the value for Sl_data_basketball.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.start_time
     *
     * @return the value of Sl_data_basketball.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.start_time
     *
     * @param startTime the value for Sl_data_basketball.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.event_date
     *
     * @return the value of Sl_data_basketball.event_date
     *
     * @mbggenerated
     */
    public String getEventDate() {
        return eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.event_date
     *
     * @param eventDate the value for Sl_data_basketball.event_date
     *
     * @mbggenerated
     */
    public void setEventDate(String eventDate) {
        this.eventDate = eventDate == null ? null : eventDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.event_type
     *
     * @return the value of Sl_data_basketball.event_type
     *
     * @mbggenerated
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.event_type
     *
     * @param eventType the value for Sl_data_basketball.event_type
     *
     * @mbggenerated
     */
    public void setEventType(String eventType) {
        this.eventType = eventType == null ? null : eventType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.event_type_abrv
     *
     * @return the value of Sl_data_basketball.event_type_abrv
     *
     * @mbggenerated
     */
    public String getEventTypeAbrv() {
        return eventTypeAbrv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.event_type_abrv
     *
     * @param eventTypeAbrv the value for Sl_data_basketball.event_type_abrv
     *
     * @mbggenerated
     */
    public void setEventTypeAbrv(String eventTypeAbrv) {
        this.eventTypeAbrv = eventTypeAbrv == null ? null : eventTypeAbrv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.home
     *
     * @return the value of Sl_data_basketball.home
     *
     * @mbggenerated
     */
    public String getHome() {
        return home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.home
     *
     * @param home the value for Sl_data_basketball.home
     *
     * @mbggenerated
     */
    public void setHome(String home) {
        this.home = home == null ? null : home.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.home_abrv
     *
     * @return the value of Sl_data_basketball.home_abrv
     *
     * @mbggenerated
     */
    public String getHomeAbrv() {
        return homeAbrv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.home_abrv
     *
     * @param homeAbrv the value for Sl_data_basketball.home_abrv
     *
     * @mbggenerated
     */
    public void setHomeAbrv(String homeAbrv) {
        this.homeAbrv = homeAbrv == null ? null : homeAbrv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.visitor
     *
     * @return the value of Sl_data_basketball.visitor
     *
     * @mbggenerated
     */
    public String getVisitor() {
        return visitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.visitor
     *
     * @param visitor the value for Sl_data_basketball.visitor
     *
     * @mbggenerated
     */
    public void setVisitor(String visitor) {
        this.visitor = visitor == null ? null : visitor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.visitor_abrv
     *
     * @return the value of Sl_data_basketball.visitor_abrv
     *
     * @mbggenerated
     */
    public String getVisitorAbrv() {
        return visitorAbrv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.visitor_abrv
     *
     * @param visitorAbrv the value for Sl_data_basketball.visitor_abrv
     *
     * @mbggenerated
     */
    public void setVisitorAbrv(String visitorAbrv) {
        this.visitorAbrv = visitorAbrv == null ? null : visitorAbrv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.event_bg_color
     *
     * @return the value of Sl_data_basketball.event_bg_color
     *
     * @mbggenerated
     */
    public String getEventBgColor() {
        return eventBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.event_bg_color
     *
     * @param eventBgColor the value for Sl_data_basketball.event_bg_color
     *
     * @mbggenerated
     */
    public void setEventBgColor(String eventBgColor) {
        this.eventBgColor = eventBgColor == null ? null : eventBgColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.contents
     *
     * @return the value of Sl_data_basketball.contents
     *
     * @mbggenerated
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.contents
     *
     * @param contents the value for Sl_data_basketball.contents
     *
     * @mbggenerated
     */
    public void setContents(String contents) {
        this.contents = contents == null ? null : contents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.home_score
     *
     * @return the value of Sl_data_basketball.home_score
     *
     * @mbggenerated
     */
    public String getHomeScore() {
        return homeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.home_score
     *
     * @param homeScore the value for Sl_data_basketball.home_score
     *
     * @mbggenerated
     */
    public void setHomeScore(String homeScore) {
        this.homeScore = homeScore == null ? null : homeScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.visitor_score
     *
     * @return the value of Sl_data_basketball.visitor_score
     *
     * @mbggenerated
     */
    public String getVisitorScore() {
        return visitorScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.visitor_score
     *
     * @param visitorScore the value for Sl_data_basketball.visitor_score
     *
     * @mbggenerated
     */
    public void setVisitorScore(String visitorScore) {
        this.visitorScore = visitorScore == null ? null : visitorScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.created
     *
     * @return the value of Sl_data_basketball.created
     *
     * @mbggenerated
     */
    public String getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.created
     *
     * @param created the value for Sl_data_basketball.created
     *
     * @mbggenerated
     */
    public void setCreated(String created) {
        this.created = created == null ? null : created.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_data_basketball.updated
     *
     * @return the value of Sl_data_basketball.updated
     *
     * @mbggenerated
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_data_basketball.updated
     *
     * @param updated the value for Sl_data_basketball.updated
     *
     * @mbggenerated
     */
    public void setUpdated(String updated) {
        this.updated = updated == null ? null : updated.trim();
    }
}