package com.zt.pojo;

public class SlResultNumWithBLOBs extends SlResultNum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.number_of_periods
     *
     * @mbggenerated
     */
    private String numberOfPeriods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.lottery_type
     *
     * @mbggenerated
     */
    private String lotteryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.data_id
     *
     * @mbggenerated
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.result_number
     *
     * @mbggenerated
     */
    private String resultNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.current_sales
     *
     * @mbggenerated
     */
    private String currentSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.jackpot_prize
     *
     * @mbggenerated
     */
    private String jackpotPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.first_prize_total
     *
     * @mbggenerated
     */
    private String firstPrizeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.first_prize_single_bonus
     *
     * @mbggenerated
     */
    private String firstPrizeSingleBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.first_prize_add
     *
     * @mbggenerated
     */
    private String firstPrizeAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.first_prize_add_prize
     *
     * @mbggenerated
     */
    private String firstPrizeAddPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.tow_prize_total
     *
     * @mbggenerated
     */
    private String towPrizeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.tow_prize_single_bonus
     *
     * @mbggenerated
     */
    private String towPrizeSingleBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.tow_prize_add
     *
     * @mbggenerated
     */
    private String towPrizeAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.tow_prize_add_prize
     *
     * @mbggenerated
     */
    private String towPrizeAddPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.three_prize_total
     *
     * @mbggenerated
     */
    private String threePrizeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.three_prize_single_bonus
     *
     * @mbggenerated
     */
    private String threePrizeSingleBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.three_prize_add
     *
     * @mbggenerated
     */
    private String threePrizeAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.three_prize_add_prize
     *
     * @mbggenerated
     */
    private String threePrizeAddPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.four_prize_total
     *
     * @mbggenerated
     */
    private String fourPrizeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.four_prize_single_bonus
     *
     * @mbggenerated
     */
    private String fourPrizeSingleBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.four_prize_add
     *
     * @mbggenerated
     */
    private String fourPrizeAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.four_prize_add_prize
     *
     * @mbggenerated
     */
    private String fourPrizeAddPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.five_prize_total
     *
     * @mbggenerated
     */
    private String fivePrizeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.five_prize_single_bonus
     *
     * @mbggenerated
     */
    private String fivePrizeSingleBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.five_prize_add
     *
     * @mbggenerated
     */
    private String fivePrizeAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.five_prize_add_prize
     *
     * @mbggenerated
     */
    private String fivePrizeAddPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.six_prize_total
     *
     * @mbggenerated
     */
    private String sixPrizeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.six_prize_single_bonus
     *
     * @mbggenerated
     */
    private String sixPrizeSingleBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.six_prize_add
     *
     * @mbggenerated
     */
    private String sixPrizeAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.six_prize_add_prize
     *
     * @mbggenerated
     */
    private String sixPrizeAddPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.array3_single
     *
     * @mbggenerated
     */
    private String array3Single;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.array3_single_prize
     *
     * @mbggenerated
     */
    private String array3SinglePrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.array3_z_three
     *
     * @mbggenerated
     */
    private String array3ZThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.array3_z_three_prize
     *
     * @mbggenerated
     */
    private String array3ZThreePrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.array3_z_six
     *
     * @mbggenerated
     */
    private String array3ZSix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.array3_z_six_prize
     *
     * @mbggenerated
     */
    private String array3ZSixPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_single
     *
     * @mbggenerated
     */
    private String _115Single;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_q2
     *
     * @mbggenerated
     */
    private String _115Q2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_q2_zx
     *
     * @mbggenerated
     */
    private String _115Q2Zx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_q3
     *
     * @mbggenerated
     */
    private String _115Q3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_q3_zx
     *
     * @mbggenerated
     */
    private String _115Q3Zx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_rx_2
     *
     * @mbggenerated
     */
    private String _115Rx2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_rx_3
     *
     * @mbggenerated
     */
    private String _115Rx3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_rx_4
     *
     * @mbggenerated
     */
    private String _115Rx4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_rx_5
     *
     * @mbggenerated
     */
    private String _115Rx5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_rx_6
     *
     * @mbggenerated
     */
    private String _115Rx6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_rx_7
     *
     * @mbggenerated
     */
    private String _115Rx7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num._11_5_rx_8
     *
     * @mbggenerated
     */
    private String _115Rx8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.dateline
     *
     * @mbggenerated
     */
    private String dateline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.created
     *
     * @mbggenerated
     */
    private String created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.updated
     *
     * @mbggenerated
     */
    private String updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.number_of_periods
     *
     * @return the value of Sl_result_num.number_of_periods
     *
     * @mbggenerated
     */
    public String getNumberOfPeriods() {
        return numberOfPeriods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.number_of_periods
     *
     * @param numberOfPeriods the value for Sl_result_num.number_of_periods
     *
     * @mbggenerated
     */
    public void setNumberOfPeriods(String numberOfPeriods) {
        this.numberOfPeriods = numberOfPeriods == null ? null : numberOfPeriods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.lottery_type
     *
     * @return the value of Sl_result_num.lottery_type
     *
     * @mbggenerated
     */
    public String getLotteryType() {
        return lotteryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.lottery_type
     *
     * @param lotteryType the value for Sl_result_num.lottery_type
     *
     * @mbggenerated
     */
    public void setLotteryType(String lotteryType) {
        this.lotteryType = lotteryType == null ? null : lotteryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.data_id
     *
     * @return the value of Sl_result_num.data_id
     *
     * @mbggenerated
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.data_id
     *
     * @param dataId the value for Sl_result_num.data_id
     *
     * @mbggenerated
     */
    public void setDataId(String dataId) {
        this.dataId = dataId == null ? null : dataId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.result_number
     *
     * @return the value of Sl_result_num.result_number
     *
     * @mbggenerated
     */
    public String getResultNumber() {
        return resultNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.result_number
     *
     * @param resultNumber the value for Sl_result_num.result_number
     *
     * @mbggenerated
     */
    public void setResultNumber(String resultNumber) {
        this.resultNumber = resultNumber == null ? null : resultNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.current_sales
     *
     * @return the value of Sl_result_num.current_sales
     *
     * @mbggenerated
     */
    public String getCurrentSales() {
        return currentSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.current_sales
     *
     * @param currentSales the value for Sl_result_num.current_sales
     *
     * @mbggenerated
     */
    public void setCurrentSales(String currentSales) {
        this.currentSales = currentSales == null ? null : currentSales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.jackpot_prize
     *
     * @return the value of Sl_result_num.jackpot_prize
     *
     * @mbggenerated
     */
    public String getJackpotPrize() {
        return jackpotPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.jackpot_prize
     *
     * @param jackpotPrize the value for Sl_result_num.jackpot_prize
     *
     * @mbggenerated
     */
    public void setJackpotPrize(String jackpotPrize) {
        this.jackpotPrize = jackpotPrize == null ? null : jackpotPrize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.first_prize_total
     *
     * @return the value of Sl_result_num.first_prize_total
     *
     * @mbggenerated
     */
    public String getFirstPrizeTotal() {
        return firstPrizeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.first_prize_total
     *
     * @param firstPrizeTotal the value for Sl_result_num.first_prize_total
     *
     * @mbggenerated
     */
    public void setFirstPrizeTotal(String firstPrizeTotal) {
        this.firstPrizeTotal = firstPrizeTotal == null ? null : firstPrizeTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.first_prize_single_bonus
     *
     * @return the value of Sl_result_num.first_prize_single_bonus
     *
     * @mbggenerated
     */
    public String getFirstPrizeSingleBonus() {
        return firstPrizeSingleBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.first_prize_single_bonus
     *
     * @param firstPrizeSingleBonus the value for Sl_result_num.first_prize_single_bonus
     *
     * @mbggenerated
     */
    public void setFirstPrizeSingleBonus(String firstPrizeSingleBonus) {
        this.firstPrizeSingleBonus = firstPrizeSingleBonus == null ? null : firstPrizeSingleBonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.first_prize_add
     *
     * @return the value of Sl_result_num.first_prize_add
     *
     * @mbggenerated
     */
    public String getFirstPrizeAdd() {
        return firstPrizeAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.first_prize_add
     *
     * @param firstPrizeAdd the value for Sl_result_num.first_prize_add
     *
     * @mbggenerated
     */
    public void setFirstPrizeAdd(String firstPrizeAdd) {
        this.firstPrizeAdd = firstPrizeAdd == null ? null : firstPrizeAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.first_prize_add_prize
     *
     * @return the value of Sl_result_num.first_prize_add_prize
     *
     * @mbggenerated
     */
    public String getFirstPrizeAddPrize() {
        return firstPrizeAddPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.first_prize_add_prize
     *
     * @param firstPrizeAddPrize the value for Sl_result_num.first_prize_add_prize
     *
     * @mbggenerated
     */
    public void setFirstPrizeAddPrize(String firstPrizeAddPrize) {
        this.firstPrizeAddPrize = firstPrizeAddPrize == null ? null : firstPrizeAddPrize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.tow_prize_total
     *
     * @return the value of Sl_result_num.tow_prize_total
     *
     * @mbggenerated
     */
    public String getTowPrizeTotal() {
        return towPrizeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.tow_prize_total
     *
     * @param towPrizeTotal the value for Sl_result_num.tow_prize_total
     *
     * @mbggenerated
     */
    public void setTowPrizeTotal(String towPrizeTotal) {
        this.towPrizeTotal = towPrizeTotal == null ? null : towPrizeTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.tow_prize_single_bonus
     *
     * @return the value of Sl_result_num.tow_prize_single_bonus
     *
     * @mbggenerated
     */
    public String getTowPrizeSingleBonus() {
        return towPrizeSingleBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.tow_prize_single_bonus
     *
     * @param towPrizeSingleBonus the value for Sl_result_num.tow_prize_single_bonus
     *
     * @mbggenerated
     */
    public void setTowPrizeSingleBonus(String towPrizeSingleBonus) {
        this.towPrizeSingleBonus = towPrizeSingleBonus == null ? null : towPrizeSingleBonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.tow_prize_add
     *
     * @return the value of Sl_result_num.tow_prize_add
     *
     * @mbggenerated
     */
    public String getTowPrizeAdd() {
        return towPrizeAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.tow_prize_add
     *
     * @param towPrizeAdd the value for Sl_result_num.tow_prize_add
     *
     * @mbggenerated
     */
    public void setTowPrizeAdd(String towPrizeAdd) {
        this.towPrizeAdd = towPrizeAdd == null ? null : towPrizeAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.tow_prize_add_prize
     *
     * @return the value of Sl_result_num.tow_prize_add_prize
     *
     * @mbggenerated
     */
    public String getTowPrizeAddPrize() {
        return towPrizeAddPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.tow_prize_add_prize
     *
     * @param towPrizeAddPrize the value for Sl_result_num.tow_prize_add_prize
     *
     * @mbggenerated
     */
    public void setTowPrizeAddPrize(String towPrizeAddPrize) {
        this.towPrizeAddPrize = towPrizeAddPrize == null ? null : towPrizeAddPrize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.three_prize_total
     *
     * @return the value of Sl_result_num.three_prize_total
     *
     * @mbggenerated
     */
    public String getThreePrizeTotal() {
        return threePrizeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.three_prize_total
     *
     * @param threePrizeTotal the value for Sl_result_num.three_prize_total
     *
     * @mbggenerated
     */
    public void setThreePrizeTotal(String threePrizeTotal) {
        this.threePrizeTotal = threePrizeTotal == null ? null : threePrizeTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.three_prize_single_bonus
     *
     * @return the value of Sl_result_num.three_prize_single_bonus
     *
     * @mbggenerated
     */
    public String getThreePrizeSingleBonus() {
        return threePrizeSingleBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.three_prize_single_bonus
     *
     * @param threePrizeSingleBonus the value for Sl_result_num.three_prize_single_bonus
     *
     * @mbggenerated
     */
    public void setThreePrizeSingleBonus(String threePrizeSingleBonus) {
        this.threePrizeSingleBonus = threePrizeSingleBonus == null ? null : threePrizeSingleBonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.three_prize_add
     *
     * @return the value of Sl_result_num.three_prize_add
     *
     * @mbggenerated
     */
    public String getThreePrizeAdd() {
        return threePrizeAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.three_prize_add
     *
     * @param threePrizeAdd the value for Sl_result_num.three_prize_add
     *
     * @mbggenerated
     */
    public void setThreePrizeAdd(String threePrizeAdd) {
        this.threePrizeAdd = threePrizeAdd == null ? null : threePrizeAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.three_prize_add_prize
     *
     * @return the value of Sl_result_num.three_prize_add_prize
     *
     * @mbggenerated
     */
    public String getThreePrizeAddPrize() {
        return threePrizeAddPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.three_prize_add_prize
     *
     * @param threePrizeAddPrize the value for Sl_result_num.three_prize_add_prize
     *
     * @mbggenerated
     */
    public void setThreePrizeAddPrize(String threePrizeAddPrize) {
        this.threePrizeAddPrize = threePrizeAddPrize == null ? null : threePrizeAddPrize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.four_prize_total
     *
     * @return the value of Sl_result_num.four_prize_total
     *
     * @mbggenerated
     */
    public String getFourPrizeTotal() {
        return fourPrizeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.four_prize_total
     *
     * @param fourPrizeTotal the value for Sl_result_num.four_prize_total
     *
     * @mbggenerated
     */
    public void setFourPrizeTotal(String fourPrizeTotal) {
        this.fourPrizeTotal = fourPrizeTotal == null ? null : fourPrizeTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.four_prize_single_bonus
     *
     * @return the value of Sl_result_num.four_prize_single_bonus
     *
     * @mbggenerated
     */
    public String getFourPrizeSingleBonus() {
        return fourPrizeSingleBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.four_prize_single_bonus
     *
     * @param fourPrizeSingleBonus the value for Sl_result_num.four_prize_single_bonus
     *
     * @mbggenerated
     */
    public void setFourPrizeSingleBonus(String fourPrizeSingleBonus) {
        this.fourPrizeSingleBonus = fourPrizeSingleBonus == null ? null : fourPrizeSingleBonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.four_prize_add
     *
     * @return the value of Sl_result_num.four_prize_add
     *
     * @mbggenerated
     */
    public String getFourPrizeAdd() {
        return fourPrizeAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.four_prize_add
     *
     * @param fourPrizeAdd the value for Sl_result_num.four_prize_add
     *
     * @mbggenerated
     */
    public void setFourPrizeAdd(String fourPrizeAdd) {
        this.fourPrizeAdd = fourPrizeAdd == null ? null : fourPrizeAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.four_prize_add_prize
     *
     * @return the value of Sl_result_num.four_prize_add_prize
     *
     * @mbggenerated
     */
    public String getFourPrizeAddPrize() {
        return fourPrizeAddPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.four_prize_add_prize
     *
     * @param fourPrizeAddPrize the value for Sl_result_num.four_prize_add_prize
     *
     * @mbggenerated
     */
    public void setFourPrizeAddPrize(String fourPrizeAddPrize) {
        this.fourPrizeAddPrize = fourPrizeAddPrize == null ? null : fourPrizeAddPrize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.five_prize_total
     *
     * @return the value of Sl_result_num.five_prize_total
     *
     * @mbggenerated
     */
    public String getFivePrizeTotal() {
        return fivePrizeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.five_prize_total
     *
     * @param fivePrizeTotal the value for Sl_result_num.five_prize_total
     *
     * @mbggenerated
     */
    public void setFivePrizeTotal(String fivePrizeTotal) {
        this.fivePrizeTotal = fivePrizeTotal == null ? null : fivePrizeTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.five_prize_single_bonus
     *
     * @return the value of Sl_result_num.five_prize_single_bonus
     *
     * @mbggenerated
     */
    public String getFivePrizeSingleBonus() {
        return fivePrizeSingleBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.five_prize_single_bonus
     *
     * @param fivePrizeSingleBonus the value for Sl_result_num.five_prize_single_bonus
     *
     * @mbggenerated
     */
    public void setFivePrizeSingleBonus(String fivePrizeSingleBonus) {
        this.fivePrizeSingleBonus = fivePrizeSingleBonus == null ? null : fivePrizeSingleBonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.five_prize_add
     *
     * @return the value of Sl_result_num.five_prize_add
     *
     * @mbggenerated
     */
    public String getFivePrizeAdd() {
        return fivePrizeAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.five_prize_add
     *
     * @param fivePrizeAdd the value for Sl_result_num.five_prize_add
     *
     * @mbggenerated
     */
    public void setFivePrizeAdd(String fivePrizeAdd) {
        this.fivePrizeAdd = fivePrizeAdd == null ? null : fivePrizeAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.five_prize_add_prize
     *
     * @return the value of Sl_result_num.five_prize_add_prize
     *
     * @mbggenerated
     */
    public String getFivePrizeAddPrize() {
        return fivePrizeAddPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.five_prize_add_prize
     *
     * @param fivePrizeAddPrize the value for Sl_result_num.five_prize_add_prize
     *
     * @mbggenerated
     */
    public void setFivePrizeAddPrize(String fivePrizeAddPrize) {
        this.fivePrizeAddPrize = fivePrizeAddPrize == null ? null : fivePrizeAddPrize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.six_prize_total
     *
     * @return the value of Sl_result_num.six_prize_total
     *
     * @mbggenerated
     */
    public String getSixPrizeTotal() {
        return sixPrizeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.six_prize_total
     *
     * @param sixPrizeTotal the value for Sl_result_num.six_prize_total
     *
     * @mbggenerated
     */
    public void setSixPrizeTotal(String sixPrizeTotal) {
        this.sixPrizeTotal = sixPrizeTotal == null ? null : sixPrizeTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.six_prize_single_bonus
     *
     * @return the value of Sl_result_num.six_prize_single_bonus
     *
     * @mbggenerated
     */
    public String getSixPrizeSingleBonus() {
        return sixPrizeSingleBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.six_prize_single_bonus
     *
     * @param sixPrizeSingleBonus the value for Sl_result_num.six_prize_single_bonus
     *
     * @mbggenerated
     */
    public void setSixPrizeSingleBonus(String sixPrizeSingleBonus) {
        this.sixPrizeSingleBonus = sixPrizeSingleBonus == null ? null : sixPrizeSingleBonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.six_prize_add
     *
     * @return the value of Sl_result_num.six_prize_add
     *
     * @mbggenerated
     */
    public String getSixPrizeAdd() {
        return sixPrizeAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.six_prize_add
     *
     * @param sixPrizeAdd the value for Sl_result_num.six_prize_add
     *
     * @mbggenerated
     */
    public void setSixPrizeAdd(String sixPrizeAdd) {
        this.sixPrizeAdd = sixPrizeAdd == null ? null : sixPrizeAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.six_prize_add_prize
     *
     * @return the value of Sl_result_num.six_prize_add_prize
     *
     * @mbggenerated
     */
    public String getSixPrizeAddPrize() {
        return sixPrizeAddPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.six_prize_add_prize
     *
     * @param sixPrizeAddPrize the value for Sl_result_num.six_prize_add_prize
     *
     * @mbggenerated
     */
    public void setSixPrizeAddPrize(String sixPrizeAddPrize) {
        this.sixPrizeAddPrize = sixPrizeAddPrize == null ? null : sixPrizeAddPrize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.array3_single
     *
     * @return the value of Sl_result_num.array3_single
     *
     * @mbggenerated
     */
    public String getArray3Single() {
        return array3Single;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.array3_single
     *
     * @param array3Single the value for Sl_result_num.array3_single
     *
     * @mbggenerated
     */
    public void setArray3Single(String array3Single) {
        this.array3Single = array3Single == null ? null : array3Single.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.array3_single_prize
     *
     * @return the value of Sl_result_num.array3_single_prize
     *
     * @mbggenerated
     */
    public String getArray3SinglePrize() {
        return array3SinglePrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.array3_single_prize
     *
     * @param array3SinglePrize the value for Sl_result_num.array3_single_prize
     *
     * @mbggenerated
     */
    public void setArray3SinglePrize(String array3SinglePrize) {
        this.array3SinglePrize = array3SinglePrize == null ? null : array3SinglePrize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.array3_z_three
     *
     * @return the value of Sl_result_num.array3_z_three
     *
     * @mbggenerated
     */
    public String getArray3ZThree() {
        return array3ZThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.array3_z_three
     *
     * @param array3ZThree the value for Sl_result_num.array3_z_three
     *
     * @mbggenerated
     */
    public void setArray3ZThree(String array3ZThree) {
        this.array3ZThree = array3ZThree == null ? null : array3ZThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.array3_z_three_prize
     *
     * @return the value of Sl_result_num.array3_z_three_prize
     *
     * @mbggenerated
     */
    public String getArray3ZThreePrize() {
        return array3ZThreePrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.array3_z_three_prize
     *
     * @param array3ZThreePrize the value for Sl_result_num.array3_z_three_prize
     *
     * @mbggenerated
     */
    public void setArray3ZThreePrize(String array3ZThreePrize) {
        this.array3ZThreePrize = array3ZThreePrize == null ? null : array3ZThreePrize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.array3_z_six
     *
     * @return the value of Sl_result_num.array3_z_six
     *
     * @mbggenerated
     */
    public String getArray3ZSix() {
        return array3ZSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.array3_z_six
     *
     * @param array3ZSix the value for Sl_result_num.array3_z_six
     *
     * @mbggenerated
     */
    public void setArray3ZSix(String array3ZSix) {
        this.array3ZSix = array3ZSix == null ? null : array3ZSix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.array3_z_six_prize
     *
     * @return the value of Sl_result_num.array3_z_six_prize
     *
     * @mbggenerated
     */
    public String getArray3ZSixPrize() {
        return array3ZSixPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.array3_z_six_prize
     *
     * @param array3ZSixPrize the value for Sl_result_num.array3_z_six_prize
     *
     * @mbggenerated
     */
    public void setArray3ZSixPrize(String array3ZSixPrize) {
        this.array3ZSixPrize = array3ZSixPrize == null ? null : array3ZSixPrize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_single
     *
     * @return the value of Sl_result_num._11_5_single
     *
     * @mbggenerated
     */
    public String get115Single() {
        return _115Single;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_single
     *
     * @param _115Single the value for Sl_result_num._11_5_single
     *
     * @mbggenerated
     */
    public void set115Single(String _115Single) {
        this._115Single = _115Single == null ? null : _115Single.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_q2
     *
     * @return the value of Sl_result_num._11_5_q2
     *
     * @mbggenerated
     */
    public String get_115Q2() {
        return _115Q2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_q2
     *
     * @param _115Q2 the value for Sl_result_num._11_5_q2
     *
     * @mbggenerated
     */
    public void set115Q2(String _115Q2) {
        this._115Q2 = _115Q2 == null ? null : _115Q2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_q2_zx
     *
     * @return the value of Sl_result_num._11_5_q2_zx
     *
     * @mbggenerated
     */
    public String get115Q2Zx() {
        return _115Q2Zx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_q2_zx
     *
     * @param _115Q2Zx the value for Sl_result_num._11_5_q2_zx
     *
     * @mbggenerated
     */
    public void set115Q2Zx(String _115Q2Zx) {
        this._115Q2Zx = _115Q2Zx == null ? null : _115Q2Zx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_q3
     *
     * @return the value of Sl_result_num._11_5_q3
     *
     * @mbggenerated
     */
    public String get115Q3() {
        return _115Q3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_q3
     *
     * @param _115Q3 the value for Sl_result_num._11_5_q3
     *
     * @mbggenerated
     */
    public void set115Q3(String _115Q3) {
        this._115Q3 = _115Q3 == null ? null : _115Q3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_q3_zx
     *
     * @return the value of Sl_result_num._11_5_q3_zx
     *
     * @mbggenerated
     */
    public String get115Q3Zx() {
        return _115Q3Zx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_q3_zx
     *
     * @param _115Q3Zx the value for Sl_result_num._11_5_q3_zx
     *
     * @mbggenerated
     */
    public void set115Q3Zx(String _115Q3Zx) {
        this._115Q3Zx = _115Q3Zx == null ? null : _115Q3Zx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_rx_2
     *
     * @return the value of Sl_result_num._11_5_rx_2
     *
     * @mbggenerated
     */
    public String get115Rx2() {
        return _115Rx2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_rx_2
     *
     * @param _115Rx2 the value for Sl_result_num._11_5_rx_2
     *
     * @mbggenerated
     */
    public void set115Rx2(String _115Rx2) {
        this._115Rx2 = _115Rx2 == null ? null : _115Rx2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_rx_3
     *
     * @return the value of Sl_result_num._11_5_rx_3
     *
     * @mbggenerated
     */
    public String get115Rx3() {
        return _115Rx3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_rx_3
     *
     * @param _115Rx3 the value for Sl_result_num._11_5_rx_3
     *
     * @mbggenerated
     */
    public void set115Rx3(String _115Rx3) {
        this._115Rx3 = _115Rx3 == null ? null : _115Rx3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_rx_4
     *
     * @return the value of Sl_result_num._11_5_rx_4
     *
     * @mbggenerated
     */
    public String get115Rx4() {
        return _115Rx4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_rx_4
     *
     * @param _115Rx4 the value for Sl_result_num._11_5_rx_4
     *
     * @mbggenerated
     */
    public void set115Rx4(String _115Rx4) {
        this._115Rx4 = _115Rx4 == null ? null : _115Rx4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_rx_5
     *
     * @return the value of Sl_result_num._11_5_rx_5
     *
     * @mbggenerated
     */
    public String get115Rx5() {
        return _115Rx5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_rx_5
     *
     * @param _115Rx5 the value for Sl_result_num._11_5_rx_5
     *
     * @mbggenerated
     */
    public void set115Rx5(String _115Rx5) {
        this._115Rx5 = _115Rx5 == null ? null : _115Rx5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_rx_6
     *
     * @return the value of Sl_result_num._11_5_rx_6
     *
     * @mbggenerated
     */
    public String get115Rx6() {
        return _115Rx6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_rx_6
     *
     * @param _115Rx6 the value for Sl_result_num._11_5_rx_6
     *
     * @mbggenerated
     */
    public void set115Rx6(String _115Rx6) {
        this._115Rx6 = _115Rx6 == null ? null : _115Rx6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_rx_7
     *
     * @return the value of Sl_result_num._11_5_rx_7
     *
     * @mbggenerated
     */
    public String get115Rx7() {
        return _115Rx7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_rx_7
     *
     * @param _115Rx7 the value for Sl_result_num._11_5_rx_7
     *
     * @mbggenerated
     */
    public void set115Rx7(String _115Rx7) {
        this._115Rx7 = _115Rx7 == null ? null : _115Rx7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num._11_5_rx_8
     *
     * @return the value of Sl_result_num._11_5_rx_8
     *
     * @mbggenerated
     */
    public String get115Rx8() {
        return _115Rx8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num._11_5_rx_8
     *
     * @param _115Rx8 the value for Sl_result_num._11_5_rx_8
     *
     * @mbggenerated
     */
    public void set115Rx8(String _115Rx8) {
        this._115Rx8 = _115Rx8 == null ? null : _115Rx8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.dateline
     *
     * @return the value of Sl_result_num.dateline
     *
     * @mbggenerated
     */
    public String getDateline() {
        return dateline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.dateline
     *
     * @param dateline the value for Sl_result_num.dateline
     *
     * @mbggenerated
     */
    public void setDateline(String dateline) {
        this.dateline = dateline == null ? null : dateline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.created
     *
     * @return the value of Sl_result_num.created
     *
     * @mbggenerated
     */
    public String getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.created
     *
     * @param created the value for Sl_result_num.created
     *
     * @mbggenerated
     */
    public void setCreated(String created) {
        this.created = created == null ? null : created.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.updated
     *
     * @return the value of Sl_result_num.updated
     *
     * @mbggenerated
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.updated
     *
     * @param updated the value for Sl_result_num.updated
     *
     * @mbggenerated
     */
    public void setUpdated(String updated) {
        this.updated = updated == null ? null : updated.trim();
    }
}