package com.zt.pojo;

import java.util.Date;

public class SlResultNum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.createdAt
     *
     * @mbggenerated
     */
    private Date createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sl_result_num.updatedAt
     *
     * @mbggenerated
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.id
     *
     * @return the value of Sl_result_num.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.id
     *
     * @param id the value for Sl_result_num.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.createdAt
     *
     * @return the value of Sl_result_num.createdAt
     *
     * @mbggenerated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.createdAt
     *
     * @param createdat the value for Sl_result_num.createdAt
     *
     * @mbggenerated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sl_result_num.updatedAt
     *
     * @return the value of Sl_result_num.updatedAt
     *
     * @mbggenerated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sl_result_num.updatedAt
     *
     * @param updatedat the value for Sl_result_num.updatedAt
     *
     * @mbggenerated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}